### ISSUE TITLE
SkinRestorerAPI not initialized

### ISSUE THREAD

**Issue by bacalhau-seco** [Dantevg/WebStats#94]
Loading the server with Webstats gives this error message.
Im on purpur 1.20.4 and SkinRestorer is on version 15.0.13, running on proxy mode
Is there anything i can do about it?

`[11:33:57 ERROR]: Error occurred while enabling WebStats v1.10.0 (Is it up to date?)
java.lang.IllegalStateException: SkinsRestorerAPI is not initialized yet! (Are you trying to access it without softDepends?)
        at net.skinsrestorer.api.SkinsRestorerProvider.get(SkinsRestorerProvider.java:35) ~[SkinsRestorer.jar:?]
        at nl.dantevg.webstats.SkinsRestorerHelper.<init>(SkinsRestorerHelper.java:22) ~[WebStats.jar:?]
        at nl.dantevg.webstats.WebStats.onEnable(WebStats.java:95) ~[WebStats.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at com.rylinaux.plugman.util.BukkitPluginUtil.enable(BukkitPluginUtil.java:135) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.util.PaperPluginUtil.enable(PaperPluginUtil.java:157) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.command.RestartCommand.execute(RestartCommand.java:127) ~[PlugManX.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:97) ~[PlugManX.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:998) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:541) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:488) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1558) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1246) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[11:33:57 INFO]: [WebStats] Disabling WebStats v1.10.0
[11:33:57 INFO]: [WebStats] Saved player ip-to-names mappings
`

**Comment by Dantevg** [comment]
I don't know off the top of my head why this would happen, but I will see if I can reproduce the bug somewhere this week. Thanks for the report!

**Comment by bacalhau-seco** [comment]
I actually did some research and apparently the API doesn't work when SkinsRestorer is in proxy mode.
Im not a developer so i dont think i can really help, but you could maybe add a setting for the plugin to stop connecting SkinsRestorerAPI

**Comment by Dantevg** [comment]
Oh, thanks for figuring it out! Maybe I can make it work automatically but otherwise I'll add a setting in the config file.

**Comment by Dantevg** [comment]
I just pushed a commit that should fix it, you can try the automatically generated jar file here: https://github.com/Dantevg/WebStats/actions/runs/9351147557/artifacts/1562766530

**Comment by bacalhau-seco** [comment]
thanks i will give it a try

**Comment by bacalhau-seco** [comment]
it works, thanks!
